- name: Configuring the redis Component
  hosts: redis
  become: yes
  tasks:
  - name: Disabling the default redis version 
    ansible.builtin.command: dnf module disable redis -y

  - name: Enable the Redis 7 version 
    ansible.builtin.command: dnf module enable redis:7 -y

  - name: Installing Redis    
    ansible.builtin.dnf:
      name: redis 
      state: present

  - name : allow remote connections
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'    
      replace: '0.0.0.0'

  - name: changing the protected mode 
    ansible.builtin.lineinfile:
      path: /etc/redis/redis.conf
      regexp: 'protected-mode'
      line: protected-mode no


  - name: Start and Enable redis
    ansible.builtin.service:
      name: redis
      state: started
      enabled: yes    